name: Kevin Reid
favicon: null
layout_spectrum: 0.4480866673402488
typography_spectrum: 0.8028085448313504
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6054558039177209
  lightness: 0.6754869455471635
  saturation: 0.1431143821682781
  rhythmicContrast: 0.2772594471462071
purpose: []
